<?php
// export_pdf_report.php

// 1. DATABASE CONNECTION
include('../../includes/db.php'); 
require_once '../../vendor/autoload.php'; 

date_default_timezone_set('Asia/Colombo');

if (!isset($conn)) { die("Error: Database connection failed."); }

ob_start();

// --- START: REPORT GENERATION LOGIC (No change here) ---
$processed_report_data = []; 
$error_message = '';

$sql = "
    SELECT t1.*, v.type AS vehicle_type, s.supplier AS supplier_name, 
    CASE WHEN t1.date < DATE_SUB(NOW(), INTERVAL 6 MONTH) THEN '🔴 OLDER THAN 6 MONTHS' ELSE '🟢 WITHIN 6 MONTHS' END AS fitness_flag
    FROM checkup t1
    INNER JOIN (SELECT vehicle_no, MAX(date) AS max_date FROM checkup GROUP BY vehicle_no) t2 
        ON t1.vehicle_no = t2.vehicle_no AND t1.date = t2.max_date
    LEFT JOIN vehicle v ON t1.vehicle_no = v.vehicle_no 
    LEFT JOIN supplier s ON t1.supplier_code = s.supplier_code             
    ORDER BY t1.supplier_code, t1.vehicle_no, t1.date DESC; 
";

if ($result = $conn->query($sql)) {
    while ($row = $result->fetch_assoc()) {
        $defective_items = [];
        $current_vehicle_type = isset($row['vehicle_type']) ? strtolower($row['vehicle_type']) : null; 
        $is_bus = ($current_vehicle_type === 'bus');
        $fitness_status_key = 'vehicle_fitness_certificate_status';
        $fitness_remark_key = 'vehicle_fitness_certificate_remark';

        // Core Logic for filtering defects
        if ($is_bus) {
            if (isset($row[$fitness_status_key]) && $row[$fitness_status_key] == 0) {
                $defective_items[] = ['item' => 'Vehicle Fitness Certificate', 'remark' => $row[$fitness_remark_key]];
            } else { continue; }
        } else {
            foreach ($row as $key => $value) {
                if (str_ends_with($key, '_status') && $key !== $fitness_status_key) {
                    $base_name = str_replace('_status', '', $key);
                    $remark_key = $base_name . '_remark';
                    if ($value == 0 && isset($row[$remark_key])) {
                        $defective_items[] = ['item' => ucwords(str_replace('_', ' ', $base_name)), 'remark' => $row[$remark_key]];
                    }
                }
            }
        }

        $common_data = ['supplier_display' => $row['supplier_code'] . ' (' . htmlspecialchars($row['supplier_name'] ?? 'N/A') . ')','vehicle_no' => $row['vehicle_no'],'date' => $row['date'],'fitness_flag' => $row['fitness_flag'],'vehicle_type' => $current_vehicle_type ];
        
        if (!empty($defective_items)) {
            $processed_report_data[] = ['common' => $common_data,'defects' => $defective_items];
        }
    }
} else { $error_message = "Query execution failed: " . $conn->error; }
// --- END: REPORT GENERATION LOGIC ---

// --- HTML HEADER CONTENT FOR mPDF ---
// This will appear on every page
$header_html = '
    <div style="border-bottom: 2px solid #333; padding-bottom: 5px; margin-bottom: 10px; font-size: 10px;">
        <table width="100%">
            <tr>
                <td style="width: 30%; font-size: 14px; font-weight: bold; border: none;">GP Garments(Pvt) Ltd.</td>
                <td style="width: 70%; text-align: right; font-size: 18px; font-weight: bold; color: #880000; border: none;">DEFECTIVE VEHICLE REPORT</td>
            </tr>
        </table>
    </div>
';

// --- HTML FOOTER CONTENT FOR mPDF ---
// This will appear on every page
$footer_html = '
    <div style="border-top: 1px solid #aaa; padding-top: 5px; font-size: 8px; color: #555;">
        <table width="100%">
            <tr>
                <td width="50%">
                    <p style="margin: 0;">Generated by: Transport Management System on ' . date('Y-m-d H:i:s') . '</p>
                </td>
                <td width="50%" style="text-align: right;">
                    Page {PAGENO} of {nbpg}
                </td>
            </tr>
        </table>
    </div>
';
$mpdf_config_header = $header_html;
$mpdf_config_footer = $footer_html;


?>

<!DOCTYPE html>
<html>
<head>
    <title>Defective Vehicle Report - PDF</title>
    <style>
        body { font-family: sans-serif; margin: 0; padding: 0; }
        
        /* Main Report Title is removed from body, now handled by mPDF Header */
        
        table { width: 100%; border-collapse: collapse; font-size: 10px; margin-top: 5px; } /* Reduced margin-top to fill space */
        th, td { border: 1px solid #777; padding: 6px; text-align: left; vertical-align: top; } 
        th { background-color: #eee; text-transform: uppercase; font-weight: bold; color: #333; }
        td { background: #fff; }
        
        .old-flag-row td { background-color: #fff0f0; } 
        
        .footer-note { font-size: 9px; margin-top: 15px; text-align: center; color: #555; }
        .empty-message { text-align:center; font-size:12px; color:#555; padding:20px; background:#f9f9f9; border:1px dashed #ccc; border-radius:6px; margin-top:10px; }
    </style>
</head>
<body>

    <h1 style="display:none;">Defective Vehicle Report</h1> 
    <p style="display:none;">Generated on: <?php echo date('Y-m-d H:i:s'); ?></p>


    <?php if (!empty($error_message)): ?>
        <p style="color:red; text-align:center; font-weight:bold;"><?php echo htmlspecialchars($error_message); ?></p>
    <?php elseif (empty($processed_report_data)): ?>
        <div class="empty-message">All OK! No defective vehicles found in the latest inspections.</div>
    <?php else: ?>
        <table>
            <thead>
                <tr>
                    <th>Vehicle #</th>
                    <th>Type</th>
                    <th>Supplier</th>
                    <th>Inspection Date</th>
                    <th>Defective Item</th>
                    <th>Remark/Reason</th>
                    <th>6-Month Flag</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($processed_report_data as $record): 
                    $common = $record['common'];
                    $defects = $record['defects'];
                    $rowspan = count($defects);
                    $row_class = ($common['fitness_flag'] == '🔴 OLDER THAN 6 MONTHS') ? 'old-flag-row' : '';
                ?>
                    <?php for ($i=0; $i<$rowspan; $i++): ?>
                        <tr class="<?php echo $row_class; ?>">
                            <?php if($i===0): ?>
                                <td rowspan="<?php echo $rowspan; ?>"><?php echo htmlspecialchars($common['vehicle_no']); ?></td>
                                <td rowspan="<?php echo $rowspan; ?>"><?php echo htmlspecialchars(ucwords($common['vehicle_type'])); ?></td>
                                <td rowspan="<?php echo $rowspan; ?>"><?php echo $common['supplier_display']; ?></td>
                                <td rowspan="<?php echo $rowspan; ?>"><?php echo htmlspecialchars($common['date']); ?></td>
                            <?php endif; ?>
                            
                            <td><?php echo htmlspecialchars($defects[$i]['item']); ?></td>
                            <td><?php echo htmlspecialchars($defects[$i]['remark']); ?></td>
                            
                            <?php if($i===0): ?>
                                <td rowspan="<?php echo $rowspan; ?>"><?php echo htmlspecialchars($common['fitness_flag']); ?></td>
                            <?php endif; ?>
                        </tr>
                    <?php endfor; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        
        <?php endif; ?>

</body>
</html>

<?php
// --- END: HTML OUTPUT FOR PDF ---
$html = ob_get_clean();

// 4. GENERATE PDF USING mPDF
$mpdf = new \Mpdf\Mpdf([
    'mode'=>'utf-8',
    'format'=>'A4', 
    
    // Set margins to leave space for the Header and Footer
    'margin_left'=>10,
    'margin_right'=>10,
    'margin_top'=>30,   // Increased margin for the header
    'margin_bottom'=>20, // Increased margin for the footer
    
    'fontSubset' => true 
]);

// 5. Apply the Header and Footer
$mpdf->SetHTMLHeader($mpdf_config_header);
$mpdf->SetHTMLFooter($mpdf_config_footer);

$mpdf->WriteHTML($html);
$filename = 'Defective_Vehicle_Report_'.date('Ymd').'.pdf';
$mpdf->Output($filename,'D');
exit;